--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 2025.3.61.0
-- Product home page: https://www.devart.com/dbforge/sql/studio
-- Script date 02-Jan-26 8:37:37 PM
-- Server version: 17.00.0925
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

USE CourseDB
GO

IF DB_NAME() <> N'CourseDB' SET NOEXEC ON
GO

--
-- Create table [dbo].[Courses]
--
PRINT (N'Create table [dbo].[Courses]')
GO
CREATE TABLE dbo.Courses (
  Id int IDENTITY,
  Title nvarchar(200) NOT NULL,
  Description nvarchar(1000) NOT NULL,
  Credits int NOT NULL,
  InstructorId int NOT NULL,
  CreatedDate datetime2 NOT NULL,
  CONSTRAINT PK_Courses PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[__EFMigrationsHistory]
--
PRINT (N'Create table [dbo].[__EFMigrationsHistory]')
GO
CREATE TABLE dbo.__EFMigrationsHistory (
  MigrationId nvarchar(150) NOT NULL,
  ProductVersion nvarchar(32) NOT NULL,
  CONSTRAINT PK___EFMigrationsHistory PRIMARY KEY CLUSTERED (MigrationId)
)
ON [PRIMARY]
GO

-- 
-- Dumping data for table __EFMigrationsHistory
--
PRINT (N'Dumping data for table __EFMigrationsHistory')
INSERT dbo.__EFMigrationsHistory(MigrationId, ProductVersion) VALUES (N'20260102112435_InitialCreate_Course', N'8.0.0')
GO

-- 
-- Dumping data for table Courses
--
PRINT (N'Dumping data for table Courses')
SET IDENTITY_INSERT dbo.Courses ON
GO
INSERT dbo.Courses(Id, Title, Description, Credits, InstructorId, CreatedDate) VALUES (1, N'Introduction to C#', N'Learn C# programming basics', 3, 1, '2026-01-02 11:24:33.6852969')
INSERT dbo.Courses(Id, Title, Description, Credits, InstructorId, CreatedDate) VALUES (2, N'Advanced ASP.NET Core', N'Master ASP.NET Core development', 4, 2, '2026-01-02 11:24:33.6852975')
GO
SET IDENTITY_INSERT dbo.Courses OFF
GO

SET NOEXEC OFF
GO