--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 2025.3.61.0
-- Product home page: https://www.devart.com/dbforge/sql/studio
-- Script date 02-Jan-26 8:38:01 PM
-- Server version: 17.00.0925
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

USE StudentDB
GO

IF DB_NAME() <> N'StudentDB' SET NOEXEC ON
GO

--
-- Create table [dbo].[Students]
--
PRINT (N'Create table [dbo].[Students]')
GO
CREATE TABLE dbo.Students (
  Id int IDENTITY,
  Name nvarchar(100) NOT NULL,
  Email nvarchar(max) NOT NULL,
  EnrollmentDate datetime2 NOT NULL,
  CONSTRAINT PK_Students PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[__EFMigrationsHistory]
--
PRINT (N'Create table [dbo].[__EFMigrationsHistory]')
GO
CREATE TABLE dbo.__EFMigrationsHistory (
  MigrationId nvarchar(150) NOT NULL,
  ProductVersion nvarchar(32) NOT NULL,
  CONSTRAINT PK___EFMigrationsHistory PRIMARY KEY CLUSTERED (MigrationId)
)
ON [PRIMARY]
GO

-- 
-- Dumping data for table __EFMigrationsHistory
--
PRINT (N'Dumping data for table __EFMigrationsHistory')
INSERT dbo.__EFMigrationsHistory(MigrationId, ProductVersion) VALUES (N'20260102112608_InitialCreate_Student', N'8.0.0')
GO

-- 
-- Dumping data for table Students
--
PRINT (N'Dumping data for table Students')
SET IDENTITY_INSERT dbo.Students ON
GO
INSERT dbo.Students(Id, Name, Email, EnrollmentDate) VALUES (1, N'John Doe', N'john@example.com', '2026-01-02 11:26:08.4992282')
INSERT dbo.Students(Id, Name, Email, EnrollmentDate) VALUES (2, N'Jane Smith', N'jane@example.com', '2026-01-02 11:26:08.4992286')
GO
SET IDENTITY_INSERT dbo.Students OFF
GO

SET NOEXEC OFF
GO